# Use the official Ubuntu base image
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive 


RUN apt-get update && apt-get install -y \
    curl \
    nodejs \
    npm

WORKDIR /app

COPY . /app

RUN npm install

EXPOSE 3004

CMD ["node", "index.js"]
